# Generated by Django 5.2.5 on 2025-08-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0007_condition_remove_shopper_postal_code_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, null=True, unique=True)),
            ],
            options={
                'ordering': ['-brand'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='exposed_wires_app.brand'),
        ),
    ]
