# Generated by Django 5.2.5 on 2025-08-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0009_alter_product_category_alter_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exposed_wires_app.product')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exposed_wires_app.shopper')),
            ],
        ),
    ]
