# Generated by Django 5.2.5 on 2025-08-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deal',
            new_name='discount',
        ),
    ]
