# Generated by Django 5.2.5 on 2025-08-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0013_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
