# Generated by Django 5.2.5 on 2025-08-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0015_alter_order_total_price_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_images',
        ),
    ]
