# Generated by Django 5.2.5 on 2025-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0016_remove_product_extra_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_role',
            field=models.CharField(choices=[('None', 'None'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='None', max_length=16),
        ),
    ]
