# Generated by Django 5.2.5 on 2025-08-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0017_seller_store_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopper',
            old_name='user',
            new_name='shopper_user',
        ),
    ]
