# Generated by Django 5.2.5 on 2025-08-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0018_rename_user_shopper_shopper_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopper',
            old_name='shopper_user',
            new_name='user',
        ),
    ]
