# Generated by Django 5.2.5 on 2025-08-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0021_filter_alter_product_discount_category_filters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='filter',
            name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
