# Generated by Django 5.2.5 on 2025-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0022_alter_product_options_remove_filter_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-clicks', '-discount', 'price', '-created_at']},
        ),
        migrations.AddField(
            model_name='store',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
