# Generated by Django 5.2.5 on 2025-08-31 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0023_alter_product_options_store_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
