# Generated by Django 5.2.5 on 2025-09-01 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0024_store_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
