# Generated by Django 5.2.5 on 2025-09-01 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0025_store_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_role',
            field=models.CharField(choices=[('None', 'none'), ('Staff', 'staff'), ('Admin', 'admin')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='store',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
