# Generated by Django 5.2.5 on 2025-09-01 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0026_alter_seller_store_role_alter_store_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
