# Generated by Django 5.2.5 on 2025-09-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed_wires_app', '0027_alter_store_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='exposed_wires_app.store'),
        ),
    ]
