# Generated by Django 5.2.5 on 2025-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_shopper',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('shopper', 'Shopper'), ('seller', 'Seller')], default='shopper', max_length=10),
        ),
    ]
