# Generated by Django 5.2.5 on 2025-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_customuser_is_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('shopper', 'Shopper'), ('seller', 'Seller'), ('admin', 'Admin')], default='shopper', max_length=10),
        ),
    ]
